export const GET_LOANS = 'GET_LOANS'
export const GET_LOAN = 'GET_LOAN'
export const ADD_LOAN = 'ADD_LOAN'
export const PAY_LOAN = 'PAY_LOAN'
export const GET_PAYMENT_HISTORY = 'GET_PAYMENT_HISTORY'
export const ITEMS_LOADING = 'ITEMS_LOADING'
